# we restrict resources consumed by container
apiVersion: v1
kind: Pod
metadata:
  name: robo-pod
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
