apiVersion: v1
kind: Pod
metadata: 
  name: pod-demo
spec:
  containers:
  - name: nginx-web
    image: nginx
    ports:  
    - containerPort: 80
    env:
      - name: db_host
        valueFrom:
          configMapKeyRef:
            name: config-demo
            key: DATABASE_HOST
      - name: db_port
        valueFrom:
          configMapKeyRef:
            name: config-demo
            key: DATABASE_PORT