apiVersion: v1
kind: Pod
metadata: 
  name: pod-secret-demo
spec:
  containers:
  - name: nginx-web-1
    image: nginx
    ports:  
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-demo