apiVersion: v1
kind: Namespace
metadata:
	name: namespace-demo
---------
apiVersion: v1 
kind: Pod
metadata:
	name: pod-demo
	namespace: namespace-demo
spec:
	containers:
	- name: nginx-demo
	  image: nginx 
	  ports:
	  - containerPort: 80
------------
apiVersion: v1 
kind: Pod 
metadata: 
	name: multi-pod-demo 
	namespace: namespace-demo
spec:
	containers:
	- name: nginx-demo-multi 
      image: nginx:1.27.2-alpine
	  ports:
	  - containerPort: 81
	- name: jenkins-demo-multi 
      image: jenkins/jenkins
	  ports:
	  - containerPort: 8080
	 
	  
	
