apiVersion: v1
kind: Pod
metadata: 
  name: pod-demo
  labels:
    app: nginx
    demo: service
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-demo
spec:
  selector: 
    app: nginx
    demo: service
  ports:
    - protcol: TCP
      port: 80
      targetPort: 80 
