apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-provision
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0c6e838ae889ec297
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  ebs-static-provision
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static-provision
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # should be lessthan EBS
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels: 
    demo: ebs-static-provision
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-static-provision
  nodeSelector:
    zone: 1a
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-static-provision
spec:
  type: LoadBalancer
  selector: 
    name: app
    labels: 
      demo: ebs-static-provision
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80